<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PcSante.Core/PcSante.Core.csproj" />
    <ProjectReference Include="../PcSante.Licensing/PcSante.Licensing.csproj" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" />
    <PackageReference Include="System.ServiceProcess.ServiceController" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="TaskScheduler" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
